# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itlo', '0004_auto_20160713_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.CharField(max_length=10)),
            ],
        ),
    ]
